#!/usr/bin/env python3
"""
Generate the 9'3"-16' height tiers for the residential grid.

Tiers 7/8/9 are Brandon's own sell prices (stock workbook + QB odd-size sheets)
and are NEVER touched by this script. The four new tiers have no workbook
coverage, so they are derived from the Clopay net book:

    solid   = round_half_up( book_net x 0.99 / (1 - margin) )
    glass   = solid + the model's existing tier-7 glass adder for that width
    inserts = glass + the model's existing tier-7 insert adder for that width

Carrying the tier-7 window adders (rather than re-deriving them from the current
window tables) keeps the window charge continuous across the 9'0" -> 9'3" step.
It also avoids importing the ~3% book drift that 9130 tiers 7/8 sit on.

Widths not printed in the Clopay grid use the book's own published rule --
"custom width pricing is next larger size plus 15%" -- so an 8'2" door prices
off the 9' row + 15%. Without this every off-grid width would silently fall back
to the next SMALLER grid row and under-charge.

Usage: python3 scripts/gen_tall_tiers.py
Rewrites: src/lib/pricing/data/residential-prices.ts
"""
import json
import re
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src/lib/pricing/data"
GRID = DATA / "residential-prices.ts"
NET = DATA / "clopay-net.json"

NEW_TIERS = ["10", "12", "14", "16"]
CUSTOM_WIDTH_UPLIFT = Decimal("1.15")  # per the book's custom-width rule
ISTORE_DISCOUNT = Decimal("0.99")

# app catalog key -> (book grid label, door margin %)
MODELS = {
    "4300": ("4300|4301|4302|4305|4310", 44),
    "4050-4051-4053": ("4050|4051|4053|4132", 43),
    "9130-9133": ("9130|9131|9132|9133", 43),
    "T50S": ("T50S|T50L", 49),
    "T52S": ("T52S|T52L", 44),
    # GD1LP-GD1SP (Gallery) is deliberately absent: its book is not one of these
    # two, and Gallery stays exactly as-is per the standing decision.
}


def money(x):
    return Decimal(str(x)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def wnum(code):
    """'15.6' -> 15.5 ft.  Note the fraction is INCHES, not decimal feet."""
    ft, _, inch = code.partition(".")
    return int(ft) + (int(inch) / 12.0 if inch else 0.0)


def parse_grid(text):
    """Read residential-prices.ts back into {model: {sizeKey: (s, g, i)}}."""
    out, order, cur = {}, [], None
    for line in text.splitlines():
        m = re.match(r'\s{2}"([^"]+)": \{\s*$', line)
        if m:
            cur = m.group(1)
            out[cur] = {}
            order.append(cur)
            continue
        m = re.match(
            r'\s*"([^"]+)": \{ "solid": ([\d.]+), "glass": ([\d.]+), "inserts": ([\d.]+) \}',
            line,
        )
        if m and cur:
            out[cur][m.group(1)] = tuple(Decimal(m.group(i)) for i in (2, 3, 4))
    return out, order


def main():
    text = GRID.read_text()
    grid, order = parse_grid(text)

    net = {}
    for r in json.loads(NET.read_text()):
        if r["spring"] == "torsion":
            net.setdefault(r["models"], {}).setdefault(r["tier"], {})[r["width"]] = r["net"]

    added = 0
    for key, (book_label, margin) in MODELS.items():
        rows = net.get(book_label, {})
        divisor = Decimal(1) - Decimal(margin) / 100
        widths7 = [k[:-2] for k in grid[key] if k.endswith("x7")]
        for tier in NEW_TIERS:
            book_widths = rows.get(tier, {})
            if not book_widths:
                continue
            ordered = sorted(book_widths, key=wnum)
            for w in widths7:
                exact = w in book_widths
                if exact:
                    src, uplift = w, Decimal(1)
                else:
                    bigger = [b for b in ordered if wnum(b) > wnum(w)]
                    if not bigger:
                        continue  # wider than anything the book prices -> Special Order
                    src, uplift = bigger[0], CUSTOM_WIDTH_UPLIFT
                base = Decimal(str(book_widths[src])) * uplift
                solid = money(base * ISTORE_DISCOUNT / divisor)
                s7, g7, i7 = grid[key][f"{w}x7"]
                glass = money(solid + (g7 - s7))
                inserts = money(glass + (i7 - g7))
                grid[key][f"{w}x{tier}"] = (solid, glass, inserts)
                added += 1
        print(f"  {key:<18} -> {sum(1 for k in grid[key] if k.split('x')[1] in NEW_TIERS)} new cells")

    header = text.split("import type", 1)[0].rstrip()
    header = re.sub(r"\n// Tiers 10/12/14/16 .*(\n//.*)*", "", header)
    header += (
        "\n// Tiers 10/12/14/16 (9'3\"-10', 10'3\"-12', 12'3\"-14', 14'3\"-16') are generated by\n"
        "// scripts/gen_tall_tiers.py from the 07/20/2026 Clopay net books. Tiers 7/8/9 are\n"
        "// Brandon's own sell prices and are not touched by that script."
    )

    body = []
    for key in order:
        body.append(f'  "{key}": {{')
        cells = sorted(
            grid[key],
            key=lambda k: (int(k.split("x")[1]), wnum(k.split("x")[0])),
        )
        for c in cells:
            s, g, i = grid[key][c]
            body.append(
                f'    "{c}": {{ "solid": {s}, "glass": {g}, "inserts": {i} }},'
            )
        body.append("  },")

    GRID.write_text(
        header
        + '\nimport type { PriceTriple } from "../types";\n\n'
        + "export const RESIDENTIAL_PRICES: Record<string, Record<string, PriceTriple>> = {\n"
        + "\n".join(body)
        + "\n};\n"
    )
    print(f"\n{added} cells added across {len(MODELS)} models")


if __name__ == "__main__":
    main()
