// AUTO-GENERATED by scripts/apply_gallery_sheet.py from the Gallery
// GD1SP/GD1LP pricing sheet (PRICING 10-8.xlsx, 8/10/2026) — grid at 43.25%. Do not edit by
// hand — re-run the script against a newer sheet.
//
// Everything here is DDS COST, before margin. The special order quote lifts
// it by the Gallery door margin at quote time, the way the 4050's glass
// tables in so-glass.ts are handled. Width bands are in inches.

export interface GalleryBand {
  /** Door width this band covers, in inches, inclusive. */
  lo: number;
  hi: number;
  /** Windows across the door in this band. */
  windows: number;
  /** Glass, and glass with decorative inserts; null where inserts are not offered. */
  glass: number;
  inserts: number | null;
}

export const GALLERY_GLASS_TYPES: { id: string; label: string }[] = [
  { id: "dsb", label: "Double strength" },
  { id: "acrylic", label: "Acrylic" },
  { id: "obscure", label: "Obscure" },
  { id: "insulated", label: "Insulated" },
  { id: "insulated_obscure", label: "Insulated obscure" },
  { id: "frosted", label: "Frosted DSB" },
  { id: "insulated_frosted", label: "Insulated frosted" },
  { id: "rain", label: "Rain DSB" },
  { id: "insulated_rain", label: "Insulated rain" },
  { id: "seeded", label: "Seeded DSB" },
  { id: "insulated_seeded", label: "Insulated seeded" },
  { id: "midnight_gray", label: "Midnight gray DSB" },
  { id: "insulated_midnight_gray", label: "Insulated midnight gray" },
  { id: "tempered_midnight_gray", label: "Tempered midnight gray" },
  { id: "insulated_tempered_midnight_gray", label: "Insulated tempered midnight gray" },
];

/** glass id -> model -> bands, narrowest first. */
export const GALLERY_GLASS: Record<string, Record<string, GalleryBand[]>> = {
  "dsb": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 131.89, inserts: 167.86 },
      { lo: 92, hi: 136, windows: 4, glass: 175.85, inserts: 223.81 },
      { lo: 138, hi: 176, windows: 6, glass: 263.78, inserts: 335.72 },
      { lo: 178, hi: 216, windows: 8, glass: 351.70, inserts: 447.62 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 175.85, inserts: 223.81 },
      { lo: 138, hi: 176, windows: 3, glass: 263.78, inserts: 335.72 },
      { lo: 178, hi: 216, windows: 4, glass: 351.70, inserts: 447.62 },
    ],
  },
  "acrylic": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 338.11, inserts: null },
      { lo: 92, hi: 136, windows: 4, glass: 450.82, inserts: null },
      { lo: 138, hi: 176, windows: 6, glass: 676.23, inserts: null },
      { lo: 178, hi: 216, windows: 8, glass: 901.64, inserts: null },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 450.82, inserts: null },
      { lo: 138, hi: 176, windows: 3, glass: 676.23, inserts: null },
      { lo: 178, hi: 216, windows: 4, glass: 901.64, inserts: null },
    ],
  },
  "obscure": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 155.87, inserts: 191.84 },
      { lo: 92, hi: 136, windows: 4, glass: 207.82, inserts: 255.78 },
      { lo: 138, hi: 176, windows: 6, glass: 311.74, inserts: 383.67 },
      { lo: 178, hi: 216, windows: 8, glass: 415.65, inserts: 511.57 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 207.82, inserts: 255.78 },
      { lo: 138, hi: 176, windows: 3, glass: 311.74, inserts: 383.67 },
      { lo: 178, hi: 216, windows: 4, glass: 415.65, inserts: 511.57 },
    ],
  },
  "insulated": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 163.06, inserts: 199.03 },
      { lo: 92, hi: 136, windows: 4, glass: 217.42, inserts: 265.37 },
      { lo: 138, hi: 176, windows: 6, glass: 326.12, inserts: 398.06 },
      { lo: 178, hi: 216, windows: 8, glass: 434.83, inserts: 530.75 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 217.42, inserts: 265.37 },
      { lo: 138, hi: 176, windows: 3, glass: 326.13, inserts: 398.06 },
      { lo: 178, hi: 216, windows: 4, glass: 434.83, inserts: 530.75 },
    ],
  },
  "insulated_obscure": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 187.04, inserts: 223.01 },
      { lo: 92, hi: 136, windows: 4, glass: 249.38, inserts: 297.35 },
      { lo: 138, hi: 176, windows: 6, glass: 374.08, inserts: 446.02 },
      { lo: 178, hi: 216, windows: 8, glass: 498.78, inserts: 594.70 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 249.39, inserts: 297.35 },
      { lo: 138, hi: 176, windows: 3, glass: 374.08, inserts: 446.02 },
      { lo: 178, hi: 216, windows: 4, glass: 498.78, inserts: 594.70 },
    ],
  },
  "frosted": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 227.81, inserts: 263.77 },
      { lo: 92, hi: 136, windows: 4, glass: 303.74, inserts: 351.70 },
      { lo: 138, hi: 176, windows: 6, glass: 455.61, inserts: 527.55 },
      { lo: 178, hi: 216, windows: 8, glass: 607.48, inserts: 703.40 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 303.74, inserts: 351.70 },
      { lo: 138, hi: 176, windows: 3, glass: 455.61, inserts: 527.55 },
      { lo: 178, hi: 216, windows: 4, glass: 607.48, inserts: 703.40 },
    ],
  },
  "insulated_frosted": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 335.72, inserts: 371.68 },
      { lo: 92, hi: 136, windows: 4, glass: 447.62, inserts: 495.58 },
      { lo: 138, hi: 176, windows: 6, glass: 671.43, inserts: 743.37 },
      { lo: 178, hi: 216, windows: 8, glass: 895.24, inserts: 991.16 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 447.62, inserts: 495.58 },
      { lo: 138, hi: 176, windows: 3, glass: 671.43, inserts: 743.37 },
      { lo: 178, hi: 216, windows: 4, glass: 895.24, inserts: 991.16 },
    ],
  },
  "rain": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 227.81, inserts: 263.77 },
      { lo: 92, hi: 136, windows: 4, glass: 303.74, inserts: 351.70 },
      { lo: 138, hi: 176, windows: 6, glass: 455.61, inserts: 527.55 },
      { lo: 178, hi: 216, windows: 8, glass: 607.48, inserts: 703.40 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 303.74, inserts: 351.70 },
      { lo: 138, hi: 176, windows: 3, glass: 455.61, inserts: 527.55 },
      { lo: 178, hi: 216, windows: 4, glass: 607.48, inserts: 703.40 },
    ],
  },
  "insulated_rain": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 335.72, inserts: 371.68 },
      { lo: 92, hi: 136, windows: 4, glass: 447.62, inserts: 495.58 },
      { lo: 138, hi: 176, windows: 6, glass: 671.43, inserts: 743.37 },
      { lo: 178, hi: 216, windows: 8, glass: 895.24, inserts: 991.16 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 447.62, inserts: 495.58 },
      { lo: 138, hi: 176, windows: 3, glass: 671.43, inserts: 743.37 },
      { lo: 178, hi: 216, windows: 4, glass: 895.24, inserts: 991.16 },
    ],
  },
  "seeded": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 311.74, inserts: 347.71 },
      { lo: 92, hi: 136, windows: 4, glass: 415.65, inserts: 463.61 },
      { lo: 138, hi: 176, windows: 6, glass: 623.47, inserts: 695.41 },
      { lo: 178, hi: 216, windows: 8, glass: 831.29, inserts: 927.21 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 415.65, inserts: 463.61 },
      { lo: 138, hi: 176, windows: 3, glass: 623.47, inserts: 695.41 },
      { lo: 178, hi: 216, windows: 4, glass: 831.29, inserts: 927.21 },
    ],
  },
  "insulated_seeded": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 419.64, inserts: 455.61 },
      { lo: 92, hi: 136, windows: 4, glass: 559.53, inserts: 607.48 },
      { lo: 138, hi: 176, windows: 6, glass: 839.29, inserts: 911.23 },
      { lo: 178, hi: 216, windows: 8, glass: 1119.05, inserts: 1214.97 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 559.53, inserts: 607.48 },
      { lo: 138, hi: 176, windows: 3, glass: 839.29, inserts: 911.23 },
      { lo: 178, hi: 216, windows: 4, glass: 1119.05, inserts: 1214.97 },
    ],
  },
  "midnight_gray": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 227.81, inserts: 263.77 },
      { lo: 92, hi: 136, windows: 4, glass: 303.74, inserts: 351.70 },
      { lo: 138, hi: 176, windows: 6, glass: 455.61, inserts: 527.55 },
      { lo: 178, hi: 216, windows: 8, glass: 607.48, inserts: 703.40 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 303.74, inserts: 351.70 },
      { lo: 138, hi: 176, windows: 3, glass: 455.61, inserts: 527.55 },
      { lo: 178, hi: 216, windows: 4, glass: 607.48, inserts: 703.40 },
    ],
  },
  "insulated_midnight_gray": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 335.72, inserts: 371.68 },
      { lo: 92, hi: 136, windows: 4, glass: 447.62, inserts: 495.58 },
      { lo: 138, hi: 176, windows: 6, glass: 671.43, inserts: 743.37 },
      { lo: 178, hi: 216, windows: 8, glass: 895.24, inserts: 991.16 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 447.62, inserts: 495.58 },
      { lo: 138, hi: 176, windows: 3, glass: 671.43, inserts: 743.37 },
      { lo: 178, hi: 216, windows: 4, glass: 895.24, inserts: 991.16 },
    ],
  },
  "tempered_midnight_gray": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 273.37, inserts: 309.34 },
      { lo: 92, hi: 136, windows: 4, glass: 364.49, inserts: 412.45 },
      { lo: 138, hi: 176, windows: 6, glass: 546.74, inserts: 618.68 },
      { lo: 178, hi: 216, windows: 8, glass: 728.98, inserts: 824.90 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 364.49, inserts: 412.45 },
      { lo: 138, hi: 176, windows: 3, glass: 546.74, inserts: 618.68 },
      { lo: 178, hi: 216, windows: 4, glass: 728.98, inserts: 824.90 },
    ],
  },
  "insulated_tempered_midnight_gray": {
    "GD1SP": [
      { lo: 0, hi: 90, windows: 3, glass: 402.86, inserts: 438.83 },
      { lo: 92, hi: 136, windows: 4, glass: 537.14, inserts: 585.10 },
      { lo: 138, hi: 176, windows: 6, glass: 805.72, inserts: 877.66 },
      { lo: 178, hi: 216, windows: 8, glass: 1074.29, inserts: 1170.21 },
    ],
    "GD1LP": [
      { lo: 92, hi: 136, windows: 2, glass: 537.14, inserts: 585.10 },
      { lo: 138, hi: 176, windows: 3, glass: 805.72, inserts: 877.66 },
      { lo: 178, hi: 216, windows: 4, glass: 1074.29, inserts: 1170.21 },
    ],
  },
};

/**
 * Ultra-Grain (and the other premium finishes) on a Gallery door: a flat
 * adder by door, single or double, in two height bands — up to 8'0", and
 * 8'2" and up (Brandon, 8/10/2026). Cost, before margin.
 */
export const GALLERY_ULTRA_GRAIN = {
  upTo8ft: { single: 158.76, double: 317.53 },
  over8ft: { single: 264.61, double: 529.22 },
} as const;
